### ISSUE TITLE
When I tried to export the ¥ symbol, it changed to・. Is this because it is not supported?

### ISSUE THREAD

**Issue by chenmmmx** [wealandwoe/ecl_array.js#1]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/69128441/163382922-c46aaf7f-c2ac-48de-a4ca-d0e6406c513e.png">
<img width="878" alt="image" src="https://user-images.githubusercontent.com/69128441/163382963-8691105f-85da-4d8f-8126-ada2a6c4ac0a.png">

**Comment by wealandwoe** [comment]
ecl.js and ecl_array.js are conversion libraries dedicated to Japanese character encodings. In particular, they enable javascript to handle Shift_JIS for Windows, called Windows-31J.
¥ symbol (YEN SIGN U+00A5) is not included in the Japanese character set (JISX0201,JISX0208). Therefore, the conversion fails.
Japanese Windows uses backslash(U+005C) or ￥(U+FFE5) to display the YEN symbol.
